# Generated by Django 4.2.7 on 2025-06-03 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mirrors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sync_latency', models.IntegerField()),
                ('echo_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('total_amplitude', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('resonance_quality', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('mirror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulses', to='mirrors.mirror')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Echo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('echo_type', models.CharField(choices=[('acquire', 'Acquire'), ('release', 'Release')], max_length=20)),
                ('beacon_address', models.CharField(max_length=100)),
                ('beacon_symbol', models.CharField(max_length=20)),
                ('magnitude', models.DecimalField(decimal_places=8, max_digits=20)),
                ('frequency', models.DecimalField(decimal_places=8, max_digits=20)),
                ('resonance', models.DecimalField(decimal_places=8, max_digits=20)),
                ('phase', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('void', 'Void')], default='pending', max_length=20)),
                ('sync_hash', models.CharField(blank=True, max_length=150)),
                ('energy_cost', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('drift', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amplitude_gain', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('gain_percentage', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pulsed_at', models.DateTimeField(auto_now_add=True)),
                ('mirror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echoes', to='mirrors.mirror')),
                ('origin_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mirrors.target')),
            ],
            options={
                'ordering': ['-pulsed_at'],
            },
        ),
    ]
