# Generated by Django 4.2.7 on 2025-06-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirrors', '0001_initial'),
        ('pulse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('binance', 'Binance'), ('okx', 'OKX'), ('bybit', 'Bybit'), ('kucoin', 'KuCoin'), ('mexc', 'MEXC'), ('gate', 'Gate.io')], max_length=20)),
                ('api_key', models.CharField(max_length=200)),
                ('api_secret', models.CharField(max_length=200)),
                ('copy_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('min_trade_amount', models.DecimalField(decimal_places=8, default=10, max_digits=20)),
                ('max_trade_amount', models.DecimalField(decimal_places=8, default=1000, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_testnet', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mirror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='mirrors.mirror')),
            ],
            options={
                'unique_together': {('mirror', 'exchange')},
            },
        ),
        migrations.AddField(
            model_name='echo',
            name='detected_platform',
            field=models.CharField(choices=[('dexscreener', 'DexScreener'), ('gmgn', 'GMGN.ai'), ('photon', 'Photon'), ('raydium', 'Raydium'), ('jupiter', 'Jupiter'), ('uniswap', 'Uniswap'), ('pancakeswap', 'PancakeSwap'), ('pump', 'Pump.fun'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='echo',
            name='entry_price',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='echo',
            name='exit_price',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='echo',
            name='platform_tx_hash',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='echo',
            name='pnl_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='echo',
            name='realized_pnl',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name='TradeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_order_id', models.CharField(blank=True, max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('filled_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('avg_price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('commission', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('filled', 'Filled'), ('partially_filled', 'Partially Filled'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('echo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='pulse.echo')),
                ('exchange_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse.exchangeconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
