# Generated by Django 4.2.7 on 2025-06-03 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('mirror_type', models.CharField(choices=[('phantom', 'Phantom - Invisible Tracker'), ('echo', 'Echo - Perfect Replicator'), ('shadow', 'Shadow - Stealth Hunter'), ('prism', 'Prism - Multi-Angle Analyzer'), ('nexus', 'Nexus - Neural Network')], max_length=20)),
                ('state', models.CharField(choices=[('sleeping', 'Sleeping'), ('hunting', 'Hunting'), ('paused', 'Paused')], default='sleeping', max_length=20)),
                ('sync_count', models.IntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pulse_frequency', models.IntegerField(default=1000)),
                ('max_echo_size', models.DecimalField(decimal_places=8, default=100, max_digits=20)),
                ('risk_threshold', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('gain_target', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('awakened_at', models.DateTimeField(auto_now_add=True)),
                ('last_pulse', models.DateTimeField(auto_now=True)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mirrors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awakened_at'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beacon_id', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, max_length=50)),
                ('echoes_captured', models.IntegerField(default=0)),
                ('perfect_syncs', models.IntegerField(default=0)),
                ('sync_quality', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_tracking', models.BooleanField(default=True)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('mirror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='mirrors.mirror')),
            ],
            options={
                'unique_together': {('mirror', 'beacon_id')},
            },
        ),
    ]
