# Generated by Django 5.1.3 on 2025-06-07 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirrors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('api_endpoint', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectedWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('private_key_encrypted', models.TextField()),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mirrors.tradingplatform')),
            ],
            options={
                'unique_together': {('user', 'address', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='TradingBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('copy_mode', models.CharField(choices=[('exact', 'Exact Copy'), ('proportional', 'Proportional'), ('fixed', 'Fixed Amount')], default='proportional', max_length=20)),
                ('max_trade_size', models.DecimalField(decimal_places=8, help_text='Maximum trade size in SOL', max_digits=20)),
                ('min_trade_size', models.DecimalField(decimal_places=8, default=0.01, max_digits=20)),
                ('daily_loss_limit', models.DecimalField(decimal_places=2, help_text='Daily loss limit in USD', max_digits=10)),
                ('take_profit_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('stop_loss_percentage', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('slippage_tolerance', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('gas_limit_multiplier', models.DecimalField(decimal_places=1, default=1.5, max_digits=3)),
                ('delay_seconds', models.IntegerField(default=0, help_text='Delay before copying trade')),
                ('total_trades', models.IntegerField(default=0)),
                ('successful_trades', models.IntegerField(default=0)),
                ('failed_trades', models.IntegerField(default=0)),
                ('total_profit', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total_loss', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mirror', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_bot', to='mirrors.mirror')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mirrors.connectedwallet')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mirrors.tradingplatform')),
            ],
        ),
        migrations.CreateModel(
            name='TradeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_tx_hash', models.CharField(max_length=200)),
                ('token_address', models.CharField(max_length=200)),
                ('token_symbol', models.CharField(max_length=50)),
                ('trade_type', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('total_value', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executing', 'Executing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('executed_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('executed_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('execution_tx_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('gas_used', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('realized_pnl', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='mirrors.tradingbot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
