# Generated by Django 5.1.3 on 2025-06-08 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirrors', '0002_tradingplatform_connectedwallet_tradingbot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('shadow', 'Shadow'), ('hawk', 'Hawk'), ('hunter', 'Hunter'), ('mirror', 'Mirror')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('active_days', models.JSONField(default=list, help_text='List of active days: 0=Monday, 6=Sunday')),
                ('active_hours_start', models.TimeField(default='00:00')),
                ('active_hours_end', models.TimeField(default='23:59')),
                ('max_transactions_hour', models.IntegerField(blank=True, help_text='Null means unlimited', null=True)),
                ('max_transactions_day', models.IntegerField(blank=True, help_text='Null means unlimited', null=True)),
                ('scan_frequency', models.CharField(default='Maximum Fast', max_length=50)),
                ('min_transaction_value', models.DecimalField(decimal_places=8, default=1.0, max_digits=20)),
                ('max_transaction_value', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('min_wallet_balance', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('token_filter_type', models.CharField(choices=[('all', 'All Tokens'), ('exclude', 'Exclude These Tokens'), ('include', 'Only These Tokens')], default='all', max_length=20)),
                ('excluded_tokens', models.TextField(blank=True, help_text='Comma-separated list of tokens to exclude')),
                ('included_tokens', models.TextField(blank=True, help_text='Comma-separated list of tokens to include')),
                ('max_retention_days', models.IntegerField(default=10, help_text='Keep transaction data for X days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('pilot', 'name')},
            },
        ),
    ]
