# Generated by Django 5.1.3 on 2025-06-09 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirrors', '0003_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, max_length=200)),
                ('tx_hash', models.CharField(db_index=True, max_length=200, unique=True)),
                ('signature', models.CharField(db_index=True, max_length=200)),
                ('token_symbol', models.CharField(max_length=50)),
                ('token_address', models.CharField(db_index=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('total_value_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('tx_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('slot', models.BigIntegerField()),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAIL', 'Fail'), ('PENDING', 'Pending')], default='SUCCESS', max_length=10)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('realized_profit_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('profit_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mirrors.agent')),
                ('linked_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_trades', to='mirrors.transaction')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['agent', 'timestamp'], name='mirrors_tra_agent_i_1c8f28_idx'), models.Index(fields=['wallet_address', 'token_address'], name='mirrors_tra_wallet__d908da_idx'), models.Index(fields=['tx_type', 'is_closed'], name='mirrors_tra_tx_type_ddb4b4_idx')],
            },
        ),
    ]
